# .goreleaser.yml
# Schema: https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    # Clean dependencies and generate code if needed
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/main.go
    binary: payment-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: rhaloubi
    name: payment-gateway-cli
  # optional footer in release notes
  footer: |
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser)

brews:
  - name: payment-cli
    description: "CLI for interacting with the payment gateway"
    homepage: "https://github.com/rhaloubi/Payment-Gateway"
    commit_author:
      name: "Reda Haloubi"
      email: "redahaloubi8@gmail.com"



