version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/main.go
    binary: payment-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: rhaloubi
    name: payment-gateway-cli
  replace_existing_artifacts: true

brews:
  - name: payment-cli
    description: "CLI for interacting with the payment gateway"
    homepage: "https://github.com/rhaloubi/Payment-Gateway"
    commit_author:
      name: "Reda Haloubi"
      email: "redahaloubi8@gmail.com"
    install: |
      bin.install "payment-cli"
