version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: linux
    main: ./cmd/main.go
    binary: payment-cli
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]

  - id: darwin
    main: ./cmd/main.go
    binary: payment-cli
    env: [CGO_ENABLED=0]
    goos: [darwin]
    goarch: [amd64, arm64]

  - id: windows
    main: ./cmd/main.go
    binary: payment-cli
    env: [CGO_ENABLED=0]
    goos: [windows]
    goarch: [amd64]

archives:
  - id: unix
    format: tar.gz
    builds: [linux, darwin]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

  - id: windows
    format: zip
    builds: [windows]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: rhaloubi
    name: Payment-Gateway
  replace_existing_artifacts: true
