// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/role_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignMerchantOwnerRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignMerchantOwnerRoleRequest) Reset() {
	*x = AssignMerchantOwnerRoleRequest{}
	mi := &file_proto_role_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignMerchantOwnerRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignMerchantOwnerRoleRequest) ProtoMessage() {}

func (x *AssignMerchantOwnerRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignMerchantOwnerRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignMerchantOwnerRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_service_proto_rawDescGZIP(), []int{0}
}

func (x *AssignMerchantOwnerRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignMerchantOwnerRoleRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type AssignMerchantOwnerRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	MerchantId    string                 `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignMerchantOwnerRoleResponse) Reset() {
	*x = AssignMerchantOwnerRoleResponse{}
	mi := &file_proto_role_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignMerchantOwnerRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignMerchantOwnerRoleResponse) ProtoMessage() {}

func (x *AssignMerchantOwnerRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignMerchantOwnerRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignMerchantOwnerRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_service_proto_rawDescGZIP(), []int{1}
}

func (x *AssignMerchantOwnerRoleResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignMerchantOwnerRoleResponse) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignMerchantOwnerRoleResponse) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *AssignMerchantOwnerRoleResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *AssignMerchantOwnerRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesRequest) Reset() {
	*x = GetUserRolesRequest{}
	mi := &file_proto_role_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesRequest) ProtoMessage() {}

func (x *GetUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRolesRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_proto_role_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_role_service_proto_rawDescGZIP(), []int{3}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Roles         []*Role                `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResponse) Reset() {
	*x = GetUserRolesResponse{}
	mi := &file_proto_role_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResponse) ProtoMessage() {}

func (x *GetUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRolesResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRolesResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetUserRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_proto_role_service_proto protoreflect.FileDescriptor

const file_proto_role_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/role_service.proto\x12\x05proto\"Z\n" +
	"\x1eAssignMerchantOwnerRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\"\xab\x01\n" +
	"\x1fAssignMerchantOwnerRoleResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"O\n" +
	"\x13GetUserRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\"*\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"s\n" +
	"\x14GetUserRolesResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12!\n" +
	"\x05roles\x18\x03 \x03(\v2\v.proto.RoleR\x05roles2\xc0\x01\n" +
	"\vRoleService\x12h\n" +
	"\x17AssignMerchantOwnerRole\x12%.proto.AssignMerchantOwnerRoleRequest\x1a&.proto.AssignMerchantOwnerRoleResponse\x12G\n" +
	"\fGetUserRoles\x12\x1a.proto.GetUserRolesRequest\x1a\x1b.proto.GetUserRolesResponseB>Z<github.com/rhaloubi/payment-gateway/auth-service/proto;protob\x06proto3"

var (
	file_proto_role_service_proto_rawDescOnce sync.Once
	file_proto_role_service_proto_rawDescData []byte
)

func file_proto_role_service_proto_rawDescGZIP() []byte {
	file_proto_role_service_proto_rawDescOnce.Do(func() {
		file_proto_role_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_role_service_proto_rawDesc), len(file_proto_role_service_proto_rawDesc)))
	})
	return file_proto_role_service_proto_rawDescData
}

var file_proto_role_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_role_service_proto_goTypes = []any{
	(*AssignMerchantOwnerRoleRequest)(nil),  // 0: proto.AssignMerchantOwnerRoleRequest
	(*AssignMerchantOwnerRoleResponse)(nil), // 1: proto.AssignMerchantOwnerRoleResponse
	(*GetUserRolesRequest)(nil),             // 2: proto.GetUserRolesRequest
	(*Role)(nil),                            // 3: proto.Role
	(*GetUserRolesResponse)(nil),            // 4: proto.GetUserRolesResponse
}
var file_proto_role_service_proto_depIdxs = []int32{
	3, // 0: proto.GetUserRolesResponse.roles:type_name -> proto.Role
	0, // 1: proto.RoleService.AssignMerchantOwnerRole:input_type -> proto.AssignMerchantOwnerRoleRequest
	2, // 2: proto.RoleService.GetUserRoles:input_type -> proto.GetUserRolesRequest
	1, // 3: proto.RoleService.AssignMerchantOwnerRole:output_type -> proto.AssignMerchantOwnerRoleResponse
	4, // 4: proto.RoleService.GetUserRoles:output_type -> proto.GetUserRolesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_role_service_proto_init() }
func file_proto_role_service_proto_init() {
	if File_proto_role_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_role_service_proto_rawDesc), len(file_proto_role_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_role_service_proto_goTypes,
		DependencyIndexes: file_proto_role_service_proto_depIdxs,
		MessageInfos:      file_proto_role_service_proto_msgTypes,
	}.Build()
	File_proto_role_service_proto = out.File
	file_proto_role_service_proto_goTypes = nil
	file_proto_role_service_proto_depIdxs = nil
}
