// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/api_key_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoByAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoByAPIKeyRequest) Reset() {
	*x = GetInfoByAPIKeyRequest{}
	mi := &file_proto_api_key_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoByAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoByAPIKeyRequest) ProtoMessage() {}

func (x *GetInfoByAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_key_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoByAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*GetInfoByAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_key_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetInfoByAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type GetInfoByAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MerchantId    string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoByAPIKeyResponse) Reset() {
	*x = GetInfoByAPIKeyResponse{}
	mi := &file_proto_api_key_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoByAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoByAPIKeyResponse) ProtoMessage() {}

func (x *GetInfoByAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_key_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoByAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*GetInfoByAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_key_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoByAPIKeyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetInfoByAPIKeyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInfoByAPIKeyResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetInfoByAPIKeyResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetInfoByAPIKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_api_key_service_proto protoreflect.FileDescriptor

const file_proto_api_key_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/api_key_service.proto\x12\x05proto\"1\n" +
	"\x16GetInfoByAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"\x97\x01\n" +
	"\x17GetInfoByAPIKeyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage2a\n" +
	"\rAPIKeyService\x12P\n" +
	"\x0fGetInfoByAPIKey\x12\x1d.proto.GetInfoByAPIKeyRequest\x1a\x1e.proto.GetInfoByAPIKeyResponseB>Z<github.com/rhaloubi/payment-gateway/auth-service/proto;protob\x06proto3"

var (
	file_proto_api_key_service_proto_rawDescOnce sync.Once
	file_proto_api_key_service_proto_rawDescData []byte
)

func file_proto_api_key_service_proto_rawDescGZIP() []byte {
	file_proto_api_key_service_proto_rawDescOnce.Do(func() {
		file_proto_api_key_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_key_service_proto_rawDesc), len(file_proto_api_key_service_proto_rawDesc)))
	})
	return file_proto_api_key_service_proto_rawDescData
}

var file_proto_api_key_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_api_key_service_proto_goTypes = []any{
	(*GetInfoByAPIKeyRequest)(nil),  // 0: proto.GetInfoByAPIKeyRequest
	(*GetInfoByAPIKeyResponse)(nil), // 1: proto.GetInfoByAPIKeyResponse
}
var file_proto_api_key_service_proto_depIdxs = []int32{
	0, // 0: proto.APIKeyService.GetInfoByAPIKey:input_type -> proto.GetInfoByAPIKeyRequest
	1, // 1: proto.APIKeyService.GetInfoByAPIKey:output_type -> proto.GetInfoByAPIKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_key_service_proto_init() }
func file_proto_api_key_service_proto_init() {
	if File_proto_api_key_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_key_service_proto_rawDesc), len(file_proto_api_key_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_key_service_proto_goTypes,
		DependencyIndexes: file_proto_api_key_service_proto_depIdxs,
		MessageInfos:      file_proto_api_key_service_proto_msgTypes,
	}.Build()
	File_proto_api_key_service_proto = out.File
	file_proto_api_key_service_proto_goTypes = nil
	file_proto_api_key_service_proto_depIdxs = nil
}
