// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/tokenization.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenizationService_TokenizeCard_FullMethodName  = "/tokenization.TokenizationService/TokenizeCard"
	TokenizationService_Detokenize_FullMethodName    = "/tokenization.TokenizationService/Detokenize"
	TokenizationService_ValidateToken_FullMethodName = "/tokenization.TokenizationService/ValidateToken"
	TokenizationService_RevokeToken_FullMethodName   = "/tokenization.TokenizationService/RevokeToken"
)

// TokenizationServiceClient is the client API for TokenizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TokenizationService provides secure card tokenization
type TokenizationServiceClient interface {
	// TokenizeCard creates a token from card data
	TokenizeCard(ctx context.Context, in *TokenizeCardRequest, opts ...grpc.CallOption) (*TokenizeCardResponse, error)
	// Detokenize retrieves card data from a token (internal only)
	Detokenize(ctx context.Context, in *DetokenizeRequest, opts ...grpc.CallOption) (*DetokenizeResponse, error)
	// ValidateToken checks if a token is valid
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	// RevokeToken invalidates a token
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
}

type tokenizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenizationServiceClient(cc grpc.ClientConnInterface) TokenizationServiceClient {
	return &tokenizationServiceClient{cc}
}

func (c *tokenizationServiceClient) TokenizeCard(ctx context.Context, in *TokenizeCardRequest, opts ...grpc.CallOption) (*TokenizeCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenizeCardResponse)
	err := c.cc.Invoke(ctx, TokenizationService_TokenizeCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizationServiceClient) Detokenize(ctx context.Context, in *DetokenizeRequest, opts ...grpc.CallOption) (*DetokenizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetokenizeResponse)
	err := c.cc.Invoke(ctx, TokenizationService_Detokenize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizationServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, TokenizationService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizationServiceClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, TokenizationService_RevokeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenizationServiceServer is the server API for TokenizationService service.
// All implementations must embed UnimplementedTokenizationServiceServer
// for forward compatibility.
//
// TokenizationService provides secure card tokenization
type TokenizationServiceServer interface {
	// TokenizeCard creates a token from card data
	TokenizeCard(context.Context, *TokenizeCardRequest) (*TokenizeCardResponse, error)
	// Detokenize retrieves card data from a token (internal only)
	Detokenize(context.Context, *DetokenizeRequest) (*DetokenizeResponse, error)
	// ValidateToken checks if a token is valid
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	// RevokeToken invalidates a token
	RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error)
	mustEmbedUnimplementedTokenizationServiceServer()
}

// UnimplementedTokenizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenizationServiceServer struct{}

func (UnimplementedTokenizationServiceServer) TokenizeCard(context.Context, *TokenizeCardRequest) (*TokenizeCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenizeCard not implemented")
}
func (UnimplementedTokenizationServiceServer) Detokenize(context.Context, *DetokenizeRequest) (*DetokenizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detokenize not implemented")
}
func (UnimplementedTokenizationServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedTokenizationServiceServer) RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeToken not implemented")
}
func (UnimplementedTokenizationServiceServer) mustEmbedUnimplementedTokenizationServiceServer() {}
func (UnimplementedTokenizationServiceServer) testEmbeddedByValue()                             {}

// UnsafeTokenizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenizationServiceServer will
// result in compilation errors.
type UnsafeTokenizationServiceServer interface {
	mustEmbedUnimplementedTokenizationServiceServer()
}

func RegisterTokenizationServiceServer(s grpc.ServiceRegistrar, srv TokenizationServiceServer) {
	// If the following call pancis, it indicates UnimplementedTokenizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenizationService_ServiceDesc, srv)
}

func _TokenizationService_TokenizeCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenizeCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).TokenizeCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_TokenizeCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).TokenizeCard(ctx, req.(*TokenizeCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenizationService_Detokenize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetokenizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).Detokenize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_Detokenize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).Detokenize(ctx, req.(*DetokenizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenizationService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenizationService_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_RevokeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).RevokeToken(ctx, req.(*RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenizationService_ServiceDesc is the grpc.ServiceDesc for TokenizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokenization.TokenizationService",
	HandlerType: (*TokenizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TokenizeCard",
			Handler:    _TokenizationService_TokenizeCard_Handler,
		},
		{
			MethodName: "Detokenize",
			Handler:    _TokenizationService_Detokenize_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _TokenizationService_ValidateToken_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _TokenizationService_RevokeToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tokenization.proto",
}
