// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/api_key_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // UUID of the user creating the key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_proto_api_key_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_key_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_key_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAPIKeyRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	KeyPrefix     string                 `protobuf:"bytes,3,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	PlainKey      string                 `protobuf:"bytes,4,opt,name=plain_key,json=plainKey,proto3" json:"plain_key,omitempty"` // ⚠️ Only shown once!
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResponse) Reset() {
	*x = CreateAPIKeyResponse{}
	mi := &file_proto_api_key_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResponse) ProtoMessage() {}

func (x *CreateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_key_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_key_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAPIKeyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateAPIKeyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyResponse) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *CreateAPIKeyResponse) GetPlainKey() string {
	if x != nil {
		return x.PlainKey
	}
	return ""
}

func (x *CreateAPIKeyResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateAPIKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type APIKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	KeyPrefix     string                 `protobuf:"bytes,3,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	LastUsedAt    string                 `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKey) Reset() {
	*x = APIKey{}
	mi := &file_proto_api_key_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKey) ProtoMessage() {}

func (x *APIKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_key_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKey.ProtoReflect.Descriptor instead.
func (*APIKey) Descriptor() ([]byte, []int) {
	return file_proto_api_key_service_proto_rawDescGZIP(), []int{2}
}

func (x *APIKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKey) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *APIKey) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *APIKey) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

func (x *APIKey) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetMerchantAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantAPIKeysRequest) Reset() {
	*x = GetMerchantAPIKeysRequest{}
	mi := &file_proto_api_key_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantAPIKeysRequest) ProtoMessage() {}

func (x *GetMerchantAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_key_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_key_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetMerchantAPIKeysRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetMerchantAPIKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []*APIKey              `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantAPIKeysResponse) Reset() {
	*x = GetMerchantAPIKeysResponse{}
	mi := &file_proto_api_key_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantAPIKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantAPIKeysResponse) ProtoMessage() {}

func (x *GetMerchantAPIKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_key_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantAPIKeysResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantAPIKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_key_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetMerchantAPIKeysResponse) GetApiKeys() []*APIKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

type DeactivateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateAPIKeyRequest) Reset() {
	*x = DeactivateAPIKeyRequest{}
	mi := &file_proto_api_key_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateAPIKeyRequest) ProtoMessage() {}

func (x *DeactivateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_key_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*DeactivateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_key_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeactivateAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeactivateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateAPIKeyResponse) Reset() {
	*x = DeactivateAPIKeyResponse{}
	mi := &file_proto_api_key_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateAPIKeyResponse) ProtoMessage() {}

func (x *DeactivateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_key_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*DeactivateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_key_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeactivateAPIKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyRequest) Reset() {
	*x = DeleteAPIKeyRequest{}
	mi := &file_proto_api_key_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyRequest) ProtoMessage() {}

func (x *DeleteAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_key_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_key_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyResponse) Reset() {
	*x = DeleteAPIKeyResponse{}
	mi := &file_proto_api_key_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyResponse) ProtoMessage() {}

func (x *DeleteAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_key_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_key_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAPIKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_api_key_service_proto protoreflect.FileDescriptor

const file_proto_api_key_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/api_key_service.proto\x12\x05proto\"i\n" +
	"\x13CreateAPIKeyRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\"\xaf\x01\n" +
	"\x14CreateAPIKeyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x03 \x01(\tR\tkeyPrefix\x12\x1b\n" +
	"\tplain_key\x18\x04 \x01(\tR\bplainKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\xa9\x01\n" +
	"\x06APIKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x03 \x01(\tR\tkeyPrefix\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12 \n" +
	"\flast_used_at\x18\x05 \x01(\tR\n" +
	"lastUsedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"<\n" +
	"\x19GetMerchantAPIKeysRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"F\n" +
	"\x1aGetMerchantAPIKeysResponse\x12(\n" +
	"\bapi_keys\x18\x01 \x03(\v2\r.proto.APIKeyR\aapiKeys\")\n" +
	"\x17DeactivateAPIKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeactivateAPIKeyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\x13DeleteAPIKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteAPIKeyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xd1\x02\n" +
	"\rAPIKeyService\x12G\n" +
	"\fCreateAPIKey\x12\x1a.proto.CreateAPIKeyRequest\x1a\x1b.proto.CreateAPIKeyResponse\x12Y\n" +
	"\x12GetMerchantAPIKeys\x12 .proto.GetMerchantAPIKeysRequest\x1a!.proto.GetMerchantAPIKeysResponse\x12S\n" +
	"\x10DeactivateAPIKey\x12\x1e.proto.DeactivateAPIKeyRequest\x1a\x1f.proto.DeactivateAPIKeyResponse\x12G\n" +
	"\fDeleteAPIKey\x12\x1a.proto.DeleteAPIKeyRequest\x1a\x1b.proto.DeleteAPIKeyResponseB>Z<github.com/rhaloubi/payment-gateway/auth-service/proto;protob\x06proto3"

var (
	file_proto_api_key_service_proto_rawDescOnce sync.Once
	file_proto_api_key_service_proto_rawDescData []byte
)

func file_proto_api_key_service_proto_rawDescGZIP() []byte {
	file_proto_api_key_service_proto_rawDescOnce.Do(func() {
		file_proto_api_key_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_key_service_proto_rawDesc), len(file_proto_api_key_service_proto_rawDesc)))
	})
	return file_proto_api_key_service_proto_rawDescData
}

var file_proto_api_key_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_api_key_service_proto_goTypes = []any{
	(*CreateAPIKeyRequest)(nil),        // 0: proto.CreateAPIKeyRequest
	(*CreateAPIKeyResponse)(nil),       // 1: proto.CreateAPIKeyResponse
	(*APIKey)(nil),                     // 2: proto.APIKey
	(*GetMerchantAPIKeysRequest)(nil),  // 3: proto.GetMerchantAPIKeysRequest
	(*GetMerchantAPIKeysResponse)(nil), // 4: proto.GetMerchantAPIKeysResponse
	(*DeactivateAPIKeyRequest)(nil),    // 5: proto.DeactivateAPIKeyRequest
	(*DeactivateAPIKeyResponse)(nil),   // 6: proto.DeactivateAPIKeyResponse
	(*DeleteAPIKeyRequest)(nil),        // 7: proto.DeleteAPIKeyRequest
	(*DeleteAPIKeyResponse)(nil),       // 8: proto.DeleteAPIKeyResponse
}
var file_proto_api_key_service_proto_depIdxs = []int32{
	2, // 0: proto.GetMerchantAPIKeysResponse.api_keys:type_name -> proto.APIKey
	0, // 1: proto.APIKeyService.CreateAPIKey:input_type -> proto.CreateAPIKeyRequest
	3, // 2: proto.APIKeyService.GetMerchantAPIKeys:input_type -> proto.GetMerchantAPIKeysRequest
	5, // 3: proto.APIKeyService.DeactivateAPIKey:input_type -> proto.DeactivateAPIKeyRequest
	7, // 4: proto.APIKeyService.DeleteAPIKey:input_type -> proto.DeleteAPIKeyRequest
	1, // 5: proto.APIKeyService.CreateAPIKey:output_type -> proto.CreateAPIKeyResponse
	4, // 6: proto.APIKeyService.GetMerchantAPIKeys:output_type -> proto.GetMerchantAPIKeysResponse
	6, // 7: proto.APIKeyService.DeactivateAPIKey:output_type -> proto.DeactivateAPIKeyResponse
	8, // 8: proto.APIKeyService.DeleteAPIKey:output_type -> proto.DeleteAPIKeyResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_api_key_service_proto_init() }
func file_proto_api_key_service_proto_init() {
	if File_proto_api_key_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_key_service_proto_rawDesc), len(file_proto_api_key_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_key_service_proto_goTypes,
		DependencyIndexes: file_proto_api_key_service_proto_depIdxs,
		MessageInfos:      file_proto_api_key_service_proto_msgTypes,
	}.Build()
	File_proto_api_key_service_proto = out.File
	file_proto_api_key_service_proto_goTypes = nil
	file_proto_api_key_service_proto_depIdxs = nil
}
