// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/tokenization.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"` // "visa", "mastercard", etc.
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`   // "credit", "debit", "prepaid"
	Last4         string                 `protobuf:"bytes,3,opt,name=last4,proto3" json:"last4,omitempty"`
	ExpMonth      int32                  `protobuf:"varint,4,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear       int32                  `protobuf:"varint,5,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,6,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardMetadata) Reset() {
	*x = CardMetadata{}
	mi := &file_proto_tokenization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardMetadata) ProtoMessage() {}

func (x *CardMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tokenization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardMetadata.ProtoReflect.Descriptor instead.
func (*CardMetadata) Descriptor() ([]byte, []int) {
	return file_proto_tokenization_proto_rawDescGZIP(), []int{0}
}

func (x *CardMetadata) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CardMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CardMetadata) GetLast4() string {
	if x != nil {
		return x.Last4
	}
	return ""
}

func (x *CardMetadata) GetExpMonth() int32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *CardMetadata) GetExpYear() int32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *CardMetadata) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type DetokenizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // UUID
	UsageType     string                 `protobuf:"bytes,4,opt,name=usage_type,json=usageType,proto3" json:"usage_type,omitempty"`             // "payment", "verification", "recurring"
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                                   // Amount in cents
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	IpAddress     string                 `protobuf:"bytes,7,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetokenizeRequest) Reset() {
	*x = DetokenizeRequest{}
	mi := &file_proto_tokenization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetokenizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetokenizeRequest) ProtoMessage() {}

func (x *DetokenizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tokenization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetokenizeRequest.ProtoReflect.Descriptor instead.
func (*DetokenizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_tokenization_proto_rawDescGZIP(), []int{1}
}

func (x *DetokenizeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DetokenizeRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *DetokenizeRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DetokenizeRequest) GetUsageType() string {
	if x != nil {
		return x.UsageType
	}
	return ""
}

func (x *DetokenizeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DetokenizeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DetokenizeRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *DetokenizeRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type DetokenizeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CardNumber     string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardholderName string                 `protobuf:"bytes,2,opt,name=cardholder_name,json=cardholderName,proto3" json:"cardholder_name,omitempty"`
	ExpMonth       int32                  `protobuf:"varint,3,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear        int32                  `protobuf:"varint,4,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	CardBrand      string                 `protobuf:"bytes,5,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	Last4          string                 `protobuf:"bytes,6,opt,name=last4,proto3" json:"last4,omitempty"`
	Error          string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetokenizeResponse) Reset() {
	*x = DetokenizeResponse{}
	mi := &file_proto_tokenization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetokenizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetokenizeResponse) ProtoMessage() {}

func (x *DetokenizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tokenization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetokenizeResponse.ProtoReflect.Descriptor instead.
func (*DetokenizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_tokenization_proto_rawDescGZIP(), []int{2}
}

func (x *DetokenizeResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *DetokenizeResponse) GetCardholderName() string {
	if x != nil {
		return x.CardholderName
	}
	return ""
}

func (x *DetokenizeResponse) GetExpMonth() int32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *DetokenizeResponse) GetExpYear() int32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *DetokenizeResponse) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *DetokenizeResponse) GetLast4() string {
	if x != nil {
		return x.Last4
	}
	return ""
}

func (x *DetokenizeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_proto_tokenization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tokenization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_tokenization_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateTokenRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Card          *CardMetadata          `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	UsageCount    int32                  `protobuf:"varint,4,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`
	IsSingleUse   bool                   `protobuf:"varint,5,opt,name=is_single_use,json=isSingleUse,proto3" json:"is_single_use,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_proto_tokenization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tokenization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_tokenization_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetCard() *CardMetadata {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *ValidateTokenResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ValidateTokenResponse) GetUsageCount() int32 {
	if x != nil {
		return x.UsageCount
	}
	return 0
}

func (x *ValidateTokenResponse) GetIsSingleUse() bool {
	if x != nil {
		return x.IsSingleUse
	}
	return false
}

func (x *ValidateTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_tokenization_proto protoreflect.FileDescriptor

const file_proto_tokenization_proto_rawDesc = "" +
	"\n" +
	"\x18proto/tokenization.proto\x12\ftokenization\"\xa8\x01\n" +
	"\fCardMetadata\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05last4\x18\x03 \x01(\tR\x05last4\x12\x1b\n" +
	"\texp_month\x18\x04 \x01(\x05R\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x05 \x01(\x05R\aexpYear\x12 \n" +
	"\vfingerprint\x18\x06 \x01(\tR\vfingerprint\"\x82\x02\n" +
	"\x11DetokenizeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"usage_type\x18\x04 \x01(\tR\tusageType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"ip_address\x18\a \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\b \x01(\tR\tuserAgent\"\xe1\x01\n" +
	"\x12DetokenizeResponse\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12'\n" +
	"\x0fcardholder_name\x18\x02 \x01(\tR\x0ecardholderName\x12\x1b\n" +
	"\texp_month\x18\x03 \x01(\x05R\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x04 \x01(\x05R\aexpYear\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x05 \x01(\tR\tcardBrand\x12\x14\n" +
	"\x05last4\x18\x06 \x01(\tR\x05last4\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"M\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\"\xd0\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12.\n" +
	"\x04card\x18\x02 \x01(\v2\x1a.tokenization.CardMetadataR\x04card\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vusage_count\x18\x04 \x01(\x05R\n" +
	"usageCount\x12\"\n" +
	"\ris_single_use\x18\x05 \x01(\bR\visSingleUse\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2\xc0\x01\n" +
	"\x13TokenizationService\x12O\n" +
	"\n" +
	"Detokenize\x12\x1f.tokenization.DetokenizeRequest\x1a .tokenization.DetokenizeResponse\x12X\n" +
	"\rValidateToken\x12\".tokenization.ValidateTokenRequest\x1a#.tokenization.ValidateTokenResponseB@Z>github.com/rhaloubi/payment-gateway/tokenization-service/protob\x06proto3"

var (
	file_proto_tokenization_proto_rawDescOnce sync.Once
	file_proto_tokenization_proto_rawDescData []byte
)

func file_proto_tokenization_proto_rawDescGZIP() []byte {
	file_proto_tokenization_proto_rawDescOnce.Do(func() {
		file_proto_tokenization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tokenization_proto_rawDesc), len(file_proto_tokenization_proto_rawDesc)))
	})
	return file_proto_tokenization_proto_rawDescData
}

var file_proto_tokenization_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_tokenization_proto_goTypes = []any{
	(*CardMetadata)(nil),          // 0: tokenization.CardMetadata
	(*DetokenizeRequest)(nil),     // 1: tokenization.DetokenizeRequest
	(*DetokenizeResponse)(nil),    // 2: tokenization.DetokenizeResponse
	(*ValidateTokenRequest)(nil),  // 3: tokenization.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 4: tokenization.ValidateTokenResponse
}
var file_proto_tokenization_proto_depIdxs = []int32{
	0, // 0: tokenization.ValidateTokenResponse.card:type_name -> tokenization.CardMetadata
	1, // 1: tokenization.TokenizationService.Detokenize:input_type -> tokenization.DetokenizeRequest
	3, // 2: tokenization.TokenizationService.ValidateToken:input_type -> tokenization.ValidateTokenRequest
	2, // 3: tokenization.TokenizationService.Detokenize:output_type -> tokenization.DetokenizeResponse
	4, // 4: tokenization.TokenizationService.ValidateToken:output_type -> tokenization.ValidateTokenResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tokenization_proto_init() }
func file_proto_tokenization_proto_init() {
	if File_proto_tokenization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tokenization_proto_rawDesc), len(file_proto_tokenization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tokenization_proto_goTypes,
		DependencyIndexes: file_proto_tokenization_proto_depIdxs,
		MessageInfos:      file_proto_tokenization_proto_msgTypes,
	}.Build()
	File_proto_tokenization_proto = out.File
	file_proto_tokenization_proto_goTypes = nil
	file_proto_tokenization_proto_depIdxs = nil
}
