// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Authorize
type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	CardToken     string                 `protobuf:"bytes,4,opt,name=card_token,json=cardToken,proto3" json:"card_token,omitempty"`
	CardBrand     string                 `protobuf:"bytes,5,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	CardLast4     string                 `protobuf:"bytes,6,opt,name=card_last4,json=cardLast4,proto3" json:"card_last4,omitempty"`
	FraudScore    int32                  `protobuf:"varint,7,opt,name=fraud_score,json=fraudScore,proto3" json:"fraud_score,omitempty"`
	CustomerEmail string                 `protobuf:"bytes,8,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	IpAddress     string                 `protobuf:"bytes,10,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *AuthorizeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AuthorizeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AuthorizeRequest) GetCardToken() string {
	if x != nil {
		return x.CardToken
	}
	return ""
}

func (x *AuthorizeRequest) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *AuthorizeRequest) GetCardLast4() string {
	if x != nil {
		return x.CardLast4
	}
	return ""
}

func (x *AuthorizeRequest) GetFraudScore() int32 {
	if x != nil {
		return x.FraudScore
	}
	return 0
}

func (x *AuthorizeRequest) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *AuthorizeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuthorizeRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuthorizeRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type AuthorizeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Approved        bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`
	AuthCode        string                 `protobuf:"bytes,4,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	ResponseCode    string                 `protobuf:"bytes,5,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,6,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	DeclineReason   string                 `protobuf:"bytes,7,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"`
	Amount          int64                  `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	AmountMad       int64                  `protobuf:"varint,9,opt,name=amount_mad,json=amountMad,proto3" json:"amount_mad,omitempty"`
	ExchangeRate    float64                `protobuf:"fixed64,10,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	ProcessingFee   int64                  `protobuf:"varint,11,opt,name=processing_fee,json=processingFee,proto3" json:"processing_fee,omitempty"`
	NetAmount       int64                  `protobuf:"varint,12,opt,name=net_amount,json=netAmount,proto3" json:"net_amount,omitempty"`
	Error           string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AuthorizeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthorizeResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *AuthorizeResponse) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

func (x *AuthorizeResponse) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *AuthorizeResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *AuthorizeResponse) GetDeclineReason() string {
	if x != nil {
		return x.DeclineReason
	}
	return ""
}

func (x *AuthorizeResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AuthorizeResponse) GetAmountMad() int64 {
	if x != nil {
		return x.AmountMad
	}
	return 0
}

func (x *AuthorizeResponse) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *AuthorizeResponse) GetProcessingFee() int64 {
	if x != nil {
		return x.ProcessingFee
	}
	return 0
}

func (x *AuthorizeResponse) GetNetAmount() int64 {
	if x != nil {
		return x.NetAmount
	}
	return 0
}

func (x *AuthorizeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // Can be partial
	MerchantId    string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_proto_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *CaptureRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CaptureRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CaptureRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type CaptureResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // captured
	CapturedAmount  int64                  `protobuf:"varint,3,opt,name=captured_amount,json=capturedAmount,proto3" json:"captured_amount,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,4,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CaptureResponse) Reset() {
	*x = CaptureResponse{}
	mi := &file_proto_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureResponse) ProtoMessage() {}

func (x *CaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureResponse.ProtoReflect.Descriptor instead.
func (*CaptureResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *CaptureResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CaptureResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaptureResponse) GetCapturedAmount() int64 {
	if x != nil {
		return x.CapturedAmount
	}
	return 0
}

func (x *CaptureResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *CaptureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VoidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidRequest) Reset() {
	*x = VoidRequest{}
	mi := &file_proto_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidRequest) ProtoMessage() {}

func (x *VoidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidRequest.ProtoReflect.Descriptor instead.
func (*VoidRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *VoidRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VoidRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *VoidRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type VoidResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,3,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VoidResponse) Reset() {
	*x = VoidResponse{}
	mi := &file_proto_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidResponse) ProtoMessage() {}

func (x *VoidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidResponse.ProtoReflect.Descriptor instead.
func (*VoidResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *VoidResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VoidResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VoidResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *VoidResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // Can be partial
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	MerchantId    string                 `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_proto_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *RefundRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RefundRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type RefundResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RefundId        string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	TransactionId   string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	RefundedAmount  int64                  `protobuf:"varint,3,opt,name=refunded_amount,json=refundedAmount,proto3" json:"refunded_amount,omitempty"`
	RemainingAmount int64                  `protobuf:"varint,4,opt,name=remaining_amount,json=remainingAmount,proto3" json:"remaining_amount,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,5,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	Error           string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_proto_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *RefundResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *RefundResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RefundResponse) GetRefundedAmount() int64 {
	if x != nil {
		return x.RefundedAmount
	}
	return 0
}

func (x *RefundResponse) GetRemainingAmount() int64 {
	if x != nil {
		return x.RemainingAmount
	}
	return 0
}

func (x *RefundResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *RefundResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_proto_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetTransactionRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type TransactionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId     string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Amount         int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	AmountMad      int64                  `protobuf:"varint,7,opt,name=amount_mad,json=amountMad,proto3" json:"amount_mad,omitempty"`
	ExchangeRate   float64                `protobuf:"fixed64,8,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	CardBrand      string                 `protobuf:"bytes,9,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	CardLast4      string                 `protobuf:"bytes,10,opt,name=card_last4,json=cardLast4,proto3" json:"card_last4,omitempty"`
	AuthCode       string                 `protobuf:"bytes,11,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	FraudScore     int32                  `protobuf:"varint,12,opt,name=fraud_score,json=fraudScore,proto3" json:"fraud_score,omitempty"`
	CapturedAmount int64                  `protobuf:"varint,13,opt,name=captured_amount,json=capturedAmount,proto3" json:"captured_amount,omitempty"`
	RefundedAmount int64                  `protobuf:"varint,14,opt,name=refunded_amount,json=refundedAmount,proto3" json:"refunded_amount,omitempty"`
	ProcessingFee  int64                  `protobuf:"varint,15,opt,name=processing_fee,json=processingFee,proto3" json:"processing_fee,omitempty"`
	NetAmount      int64                  `protobuf:"varint,16,opt,name=net_amount,json=netAmount,proto3" json:"net_amount,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AuthorizedAt   string                 `protobuf:"bytes,18,opt,name=authorized_at,json=authorizedAt,proto3" json:"authorized_at,omitempty"`
	CapturedAt     string                 `protobuf:"bytes,19,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	Error          string                 `protobuf:"bytes,20,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_proto_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *TransactionResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionResponse) GetAmountMad() int64 {
	if x != nil {
		return x.AmountMad
	}
	return 0
}

func (x *TransactionResponse) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *TransactionResponse) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *TransactionResponse) GetCardLast4() string {
	if x != nil {
		return x.CardLast4
	}
	return ""
}

func (x *TransactionResponse) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

func (x *TransactionResponse) GetFraudScore() int32 {
	if x != nil {
		return x.FraudScore
	}
	return 0
}

func (x *TransactionResponse) GetCapturedAmount() int64 {
	if x != nil {
		return x.CapturedAmount
	}
	return 0
}

func (x *TransactionResponse) GetRefundedAmount() int64 {
	if x != nil {
		return x.RefundedAmount
	}
	return 0
}

func (x *TransactionResponse) GetProcessingFee() int64 {
	if x != nil {
		return x.ProcessingFee
	}
	return 0
}

func (x *TransactionResponse) GetNetAmount() int64 {
	if x != nil {
		return x.NetAmount
	}
	return 0
}

func (x *TransactionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionResponse) GetAuthorizedAt() string {
	if x != nil {
		return x.AuthorizedAt
	}
	return ""
}

func (x *TransactionResponse) GetCapturedAt() string {
	if x != nil {
		return x.CapturedAt
	}
	return ""
}

func (x *TransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_proto_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *ListTransactionsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTransactionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTransactionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionResponse `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_proto_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *ListTransactionsResponse) GetTransactions() []*TransactionResponse {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTransactionsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_transaction_proto protoreflect.FileDescriptor

const file_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"\x17proto/transaction.proto\x12\vtransaction\"\xec\x02\n" +
	"\x10AuthorizeRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"card_token\x18\x04 \x01(\tR\tcardToken\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x05 \x01(\tR\tcardBrand\x12\x1d\n" +
	"\n" +
	"card_last4\x18\x06 \x01(\tR\tcardLast4\x12\x1f\n" +
	"\vfraud_score\x18\a \x01(\x05R\n" +
	"fraudScore\x12%\n" +
	"\x0ecustomer_email\x18\b \x01(\tR\rcustomerEmail\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"ip_address\x18\n" +
	" \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\v \x01(\tR\tuserAgent\"\xba\x03\n" +
	"\x11AuthorizeResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\x12\x1b\n" +
	"\tauth_code\x18\x04 \x01(\tR\bauthCode\x12#\n" +
	"\rresponse_code\x18\x05 \x01(\tR\fresponseCode\x12)\n" +
	"\x10response_message\x18\x06 \x01(\tR\x0fresponseMessage\x12%\n" +
	"\x0edecline_reason\x18\a \x01(\tR\rdeclineReason\x12\x16\n" +
	"\x06amount\x18\b \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"amount_mad\x18\t \x01(\x03R\tamountMad\x12#\n" +
	"\rexchange_rate\x18\n" +
	" \x01(\x01R\fexchangeRate\x12%\n" +
	"\x0eprocessing_fee\x18\v \x01(\x03R\rprocessingFee\x12\x1d\n" +
	"\n" +
	"net_amount\x18\f \x01(\x03R\tnetAmount\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\"p\n" +
	"\x0eCaptureRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\"\xba\x01\n" +
	"\x0fCaptureResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fcaptured_amount\x18\x03 \x01(\x03R\x0ecapturedAmount\x12)\n" +
	"\x10response_message\x18\x04 \x01(\tR\x0fresponseMessage\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"m\n" +
	"\vVoidRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x8e\x01\n" +
	"\fVoidResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10response_message\x18\x03 \x01(\tR\x0fresponseMessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x87\x01\n" +
	"\rRefundRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\"\xe9\x01\n" +
	"\x0eRefundResponse\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12'\n" +
	"\x0frefunded_amount\x18\x03 \x01(\x03R\x0erefundedAmount\x12)\n" +
	"\x10remaining_amount\x18\x04 \x01(\x03R\x0fremainingAmount\x12)\n" +
	"\x10response_message\x18\x05 \x01(\tR\x0fresponseMessage\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"_\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\"\xf9\x04\n" +
	"\x13TransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"amount_mad\x18\a \x01(\x03R\tamountMad\x12#\n" +
	"\rexchange_rate\x18\b \x01(\x01R\fexchangeRate\x12\x1d\n" +
	"\n" +
	"card_brand\x18\t \x01(\tR\tcardBrand\x12\x1d\n" +
	"\n" +
	"card_last4\x18\n" +
	" \x01(\tR\tcardLast4\x12\x1b\n" +
	"\tauth_code\x18\v \x01(\tR\bauthCode\x12\x1f\n" +
	"\vfraud_score\x18\f \x01(\x05R\n" +
	"fraudScore\x12'\n" +
	"\x0fcaptured_amount\x18\r \x01(\x03R\x0ecapturedAmount\x12'\n" +
	"\x0frefunded_amount\x18\x0e \x01(\x03R\x0erefundedAmount\x12%\n" +
	"\x0eprocessing_fee\x18\x0f \x01(\x03R\rprocessingFee\x12\x1d\n" +
	"\n" +
	"net_amount\x18\x10 \x01(\x03R\tnetAmount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt\x12#\n" +
	"\rauthorized_at\x18\x12 \x01(\tR\fauthorizedAt\x12\x1f\n" +
	"\vcaptured_at\x18\x13 \x01(\tR\n" +
	"capturedAt\x12\x14\n" +
	"\x05error\x18\x14 \x01(\tR\x05error\"\x80\x01\n" +
	"\x17ListTransactionsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x8c\x01\n" +
	"\x18ListTransactionsResponse\x12D\n" +
	"\ftransactions\x18\x01 \x03(\v2 .transaction.TransactionResponseR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xdf\x03\n" +
	"\x12TransactionService\x12J\n" +
	"\tAuthorize\x12\x1d.transaction.AuthorizeRequest\x1a\x1e.transaction.AuthorizeResponse\x12D\n" +
	"\aCapture\x12\x1b.transaction.CaptureRequest\x1a\x1c.transaction.CaptureResponse\x12;\n" +
	"\x04Void\x12\x18.transaction.VoidRequest\x1a\x19.transaction.VoidResponse\x12A\n" +
	"\x06Refund\x12\x1a.transaction.RefundRequest\x1a\x1b.transaction.RefundResponse\x12V\n" +
	"\x0eGetTransaction\x12\".transaction.GetTransactionRequest\x1a .transaction.TransactionResponse\x12_\n" +
	"\x10ListTransactions\x12$.transaction.ListTransactionsRequest\x1a%.transaction.ListTransactionsResponseB?Z=github.com/rhaloubi/payment-gateway/transaction-service/protob\x06proto3"

var (
	file_proto_transaction_proto_rawDescOnce sync.Once
	file_proto_transaction_proto_rawDescData []byte
)

func file_proto_transaction_proto_rawDescGZIP() []byte {
	file_proto_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_proto_rawDesc), len(file_proto_transaction_proto_rawDesc)))
	})
	return file_proto_transaction_proto_rawDescData
}

var file_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_transaction_proto_goTypes = []any{
	(*AuthorizeRequest)(nil),         // 0: transaction.AuthorizeRequest
	(*AuthorizeResponse)(nil),        // 1: transaction.AuthorizeResponse
	(*CaptureRequest)(nil),           // 2: transaction.CaptureRequest
	(*CaptureResponse)(nil),          // 3: transaction.CaptureResponse
	(*VoidRequest)(nil),              // 4: transaction.VoidRequest
	(*VoidResponse)(nil),             // 5: transaction.VoidResponse
	(*RefundRequest)(nil),            // 6: transaction.RefundRequest
	(*RefundResponse)(nil),           // 7: transaction.RefundResponse
	(*GetTransactionRequest)(nil),    // 8: transaction.GetTransactionRequest
	(*TransactionResponse)(nil),      // 9: transaction.TransactionResponse
	(*ListTransactionsRequest)(nil),  // 10: transaction.ListTransactionsRequest
	(*ListTransactionsResponse)(nil), // 11: transaction.ListTransactionsResponse
}
var file_proto_transaction_proto_depIdxs = []int32{
	9,  // 0: transaction.ListTransactionsResponse.transactions:type_name -> transaction.TransactionResponse
	0,  // 1: transaction.TransactionService.Authorize:input_type -> transaction.AuthorizeRequest
	2,  // 2: transaction.TransactionService.Capture:input_type -> transaction.CaptureRequest
	4,  // 3: transaction.TransactionService.Void:input_type -> transaction.VoidRequest
	6,  // 4: transaction.TransactionService.Refund:input_type -> transaction.RefundRequest
	8,  // 5: transaction.TransactionService.GetTransaction:input_type -> transaction.GetTransactionRequest
	10, // 6: transaction.TransactionService.ListTransactions:input_type -> transaction.ListTransactionsRequest
	1,  // 7: transaction.TransactionService.Authorize:output_type -> transaction.AuthorizeResponse
	3,  // 8: transaction.TransactionService.Capture:output_type -> transaction.CaptureResponse
	5,  // 9: transaction.TransactionService.Void:output_type -> transaction.VoidResponse
	7,  // 10: transaction.TransactionService.Refund:output_type -> transaction.RefundResponse
	9,  // 11: transaction.TransactionService.GetTransaction:output_type -> transaction.TransactionResponse
	11, // 12: transaction.TransactionService.ListTransactions:output_type -> transaction.ListTransactionsResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_transaction_proto_init() }
func file_proto_transaction_proto_init() {
	if File_proto_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_proto_rawDesc), len(file_proto_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transaction_proto_depIdxs,
		MessageInfos:      file_proto_transaction_proto_msgTypes,
	}.Build()
	File_proto_transaction_proto = out.File
	file_proto_transaction_proto_goTypes = nil
	file_proto_transaction_proto_depIdxs = nil
}
