FROM golang:1.25.5-alpine AS builder

WORKDIR /app

# Install git only if needed for private modules
RUN apk add --no-cache git

# Dependency caching
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

# Build static binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" \
    -o merchant-service cmd/main.go

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" -o merchant-migrate cmd/migrate/main.go

FROM scratch

COPY --from=builder /app/merchant-service /merchant-service
COPY --from=builder /app/merchant-migrate /merchant-migrate

# Document port
EXPOSE 8002

# Run service
ENTRYPOINT ["/merchant-service"]
