FROM golang:1.25.5-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" \
    -o transaction-service ./cmd

FROM scratch

COPY --from=builder /app/transaction-service /transaction-service

EXPOSE 50053

ENTRYPOINT ["/transaction-service"]
