FROM golang:1.25.5-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" -o auth-service cmd/main.go

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" -o auth-migrate cmd/migrate/main.go

FROM alpine:3.19

COPY --from=builder /app/auth-service /auth-service
COPY --from=builder /app/auth-migrate /auth-migrate

EXPOSE 8001
EXPOSE 50051

ENTRYPOINT ["/auth-service"]
