FROM golang:1.21-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" \
    -o auth-service cmd/main.go

FROM scratch

COPY --from=builder /app/auth-service /auth-service

# Document both ports
EXPOSE 8001
EXPOSE 50051

ENTRYPOINT ["/auth-service"]
