# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PaymentCli < Formula
  desc "CLI for interacting with the payment gateway"
  homepage "https://github.com/rhaloubi/Payment-Gateway"
  version "1.0.1-SNAPSHOT-fc32240"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rhaloubi/payment-gateway-cli/releases/download/v1.0.1/payment-gateway-cli_darwin_amd64.tar.gz"
      sha256 "2748da9c138d2aadaff43084aa61bbc03c6bc19f8b817a644a0827fab18ff0da"

      def install
        bin.install "payment-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rhaloubi/payment-gateway-cli/releases/download/v1.0.1/payment-gateway-cli_darwin_arm64.tar.gz"
      sha256 "75c324c3a3db6e730763d752d00997a34065d537d4e9579310a16cb5c202900c"

      def install
        bin.install "payment-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rhaloubi/payment-gateway-cli/releases/download/v1.0.1/payment-gateway-cli_linux_amd64.tar.gz"
      sha256 "bb13c74272ee89faa474236767b70a24d2b94e75a6d636499834f855d8abb9f5"
      def install
        bin.install "payment-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rhaloubi/payment-gateway-cli/releases/download/v1.0.1/payment-gateway-cli_linux_arm64.tar.gz"
      sha256 "653e398a32b3a5a293cd4c951bba361a882852582c591f9b2bce6bf56b8e7434"
      def install
        bin.install "payment-cli"
      end
    end
  end
end
